name: Trigger Local Refresh

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: self-hosted
    steps:
      - name: Wywołanie endpointu refresh
        run: |
          curl -X POST https://bf3b-31-0-24-193.ngrok-free.app/actuator/refresh
