name: Trigger Actuator Refresh

on:
  push:
    branches:
      - main

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API to trigger webhook
        run: |
          curl --location --request POST 'https://bf3b-31-0-24-193.ngrok-free.app/actuator/refresh'
